#!/usr/bin/env bun
// Regenerate src/assets.ts by enumerating ui/dist so every chunk produced
// by Vite (mermaid, gpt-tokenizer, etc.) gets embedded into the compiled
// binary. Run after `bun run build:ui` and before `bun run build:bin`.

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const distDir = join(root, "ui/dist");
const outFile = join(root, "src/assets.ts");

const files: string[] = [];
(function walk(dir: string) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full);
    else files.push(full);
  }
})(distDir);
files.sort();

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".map": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
};

const imports: string[] = [];
const entries: string[] = [];

files.forEach((abs, i) => {
  const rel = relative(distDir, abs).split("\\").join("/");
  const ext = rel.slice(rel.lastIndexOf("."));
  const mime = MIME[ext];
  if (!mime) {
    console.warn(`gen-assets: skipping ${rel} (unknown extension ${ext})`);
    return;
  }
  const v = `a${i}`;
  imports.push(`import ${v} from "../ui/dist/${rel}" with { type: "text" };`);
  const route = rel === "index.html" ? "/" : `/${rel}`;
  entries.push(`  ${JSON.stringify(route)}: { body: ${v}, type: ${JSON.stringify(mime)} },`);
  if (rel === "index.html") {
    entries.push(`  "/index.html": { body: ${v}, type: ${JSON.stringify(mime)} },`);
  }
});

const body = `// AUTO-GENERATED by scripts/gen-assets.ts — do not edit by hand.
${imports.join("\n")}

export const ASSETS: Record<string, { body: string; type: string }> = {
${entries.join("\n")}
};
`;

writeFileSync(outFile, body);
console.log(`gen-assets: wrote ${files.length} assets to ${relative(root, outFile)}`);
