// AUTO-GENERATED by scripts/gen-assets.ts — do not edit by hand.
import a0 from "../ui/dist/assets/_baseUniq.js" with { type: "text" };
import a1 from "../ui/dist/assets/app.css" with { type: "text" };
import a2 from "../ui/dist/assets/app.js" with { type: "text" };
import a3 from "../ui/dist/assets/arc.js" with { type: "text" };
import a4 from "../ui/dist/assets/architectureDiagram-Q4EWVU46.js" with { type: "text" };
import a5 from "../ui/dist/assets/blockDiagram-DXYQGD6D.js" with { type: "text" };
import a6 from "../ui/dist/assets/c4Diagram-AHTNJAMY.js" with { type: "text" };
import a7 from "../ui/dist/assets/channel.js" with { type: "text" };
import a8 from "../ui/dist/assets/chunk-4BX2VUAB.js" with { type: "text" };
import a9 from "../ui/dist/assets/chunk-4TB4RGXK.js" with { type: "text" };
import a10 from "../ui/dist/assets/chunk-55IACEB6.js" with { type: "text" };
import a11 from "../ui/dist/assets/chunk-EDXVE4YY.js" with { type: "text" };
import a12 from "../ui/dist/assets/chunk-FMBD7UC4.js" with { type: "text" };
import a13 from "../ui/dist/assets/chunk-OYMX7WX6.js" with { type: "text" };
import a14 from "../ui/dist/assets/chunk-QZHKN3VN.js" with { type: "text" };
import a15 from "../ui/dist/assets/chunk-YZCP3GAM.js" with { type: "text" };
import a16 from "../ui/dist/assets/classDiagram-6PBFFD2Q.js" with { type: "text" };
import a17 from "../ui/dist/assets/classDiagram-v2-HSJHXN6E.js" with { type: "text" };
import a18 from "../ui/dist/assets/clone.js" with { type: "text" };
import a19 from "../ui/dist/assets/cose-bilkent-S5V4N54A.js" with { type: "text" };
import a20 from "../ui/dist/assets/cytoscape.esm.js" with { type: "text" };
import a21 from "../ui/dist/assets/dagre-KV5264BT.js" with { type: "text" };
import a22 from "../ui/dist/assets/defaultLocale.js" with { type: "text" };
import a23 from "../ui/dist/assets/diagram-5BDNPKRD.js" with { type: "text" };
import a24 from "../ui/dist/assets/diagram-G4DWMVQ6.js" with { type: "text" };
import a25 from "../ui/dist/assets/diagram-MMDJMWI5.js" with { type: "text" };
import a26 from "../ui/dist/assets/diagram-TYMM5635.js" with { type: "text" };
import a27 from "../ui/dist/assets/erDiagram-SMLLAGMA.js" with { type: "text" };
import a28 from "../ui/dist/assets/flowDiagram-DWJPFMVM.js" with { type: "text" };
import a29 from "../ui/dist/assets/ganttDiagram-T4ZO3ILL.js" with { type: "text" };
import a30 from "../ui/dist/assets/gitGraphDiagram-UUTBAWPF.js" with { type: "text" };
import a31 from "../ui/dist/assets/gpt-4o.js" with { type: "text" };
import a32 from "../ui/dist/assets/graph.js" with { type: "text" };
import a33 from "../ui/dist/assets/infoDiagram-42DDH7IO.js" with { type: "text" };
import a34 from "../ui/dist/assets/init.js" with { type: "text" };
import a35 from "../ui/dist/assets/ishikawaDiagram-UXIWVN3A.js" with { type: "text" };
import a36 from "../ui/dist/assets/journeyDiagram-VCZTEJTY.js" with { type: "text" };
import a37 from "../ui/dist/assets/kanban-definition-6JOO6SKY.js" with { type: "text" };
import a38 from "../ui/dist/assets/katex.js" with { type: "text" };
import a39 from "../ui/dist/assets/layout.js" with { type: "text" };
import a40 from "../ui/dist/assets/linear.js" with { type: "text" };
import a41 from "../ui/dist/assets/mermaid.core.js" with { type: "text" };
import a42 from "../ui/dist/assets/min.js" with { type: "text" };
import a43 from "../ui/dist/assets/mindmap-definition-QFDTVHPH.js" with { type: "text" };
import a44 from "../ui/dist/assets/ordinal.js" with { type: "text" };
import a45 from "../ui/dist/assets/pieDiagram-DEJITSTG.js" with { type: "text" };
import a46 from "../ui/dist/assets/quadrantDiagram-34T5L4WZ.js" with { type: "text" };
import a47 from "../ui/dist/assets/requirementDiagram-MS252O5E.js" with { type: "text" };
import a48 from "../ui/dist/assets/sankeyDiagram-XADWPNL6.js" with { type: "text" };
import a49 from "../ui/dist/assets/sequenceDiagram-FGHM5R23.js" with { type: "text" };
import a50 from "../ui/dist/assets/stateDiagram-FHFEXIEX.js" with { type: "text" };
import a51 from "../ui/dist/assets/stateDiagram-v2-QKLJ7IA2.js" with { type: "text" };
import a52 from "../ui/dist/assets/timeline-definition-GMOUNBTQ.js" with { type: "text" };
import a53 from "../ui/dist/assets/vennDiagram-DHZGUBPP.js" with { type: "text" };
import a54 from "../ui/dist/assets/wardley-RL74JXVD.js" with { type: "text" };
import a55 from "../ui/dist/assets/wardleyDiagram-NUSXRM2D.js" with { type: "text" };
import a56 from "../ui/dist/assets/xychartDiagram-5P7HB3ND.js" with { type: "text" };
import a57 from "../ui/dist/index.html" with { type: "text" };

export const ASSETS: Record<string, { body: string; type: string }> = {
  "/assets/_baseUniq.js": { body: a0, type: "application/javascript; charset=utf-8" },
  "/assets/app.css": { body: a1, type: "text/css; charset=utf-8" },
  "/assets/app.js": { body: a2, type: "application/javascript; charset=utf-8" },
  "/assets/arc.js": { body: a3, type: "application/javascript; charset=utf-8" },
  "/assets/architectureDiagram-Q4EWVU46.js": { body: a4, type: "application/javascript; charset=utf-8" },
  "/assets/blockDiagram-DXYQGD6D.js": { body: a5, type: "application/javascript; charset=utf-8" },
  "/assets/c4Diagram-AHTNJAMY.js": { body: a6, type: "application/javascript; charset=utf-8" },
  "/assets/channel.js": { body: a7, type: "application/javascript; charset=utf-8" },
  "/assets/chunk-4BX2VUAB.js": { body: a8, type: "application/javascript; charset=utf-8" },
  "/assets/chunk-4TB4RGXK.js": { body: a9, type: "application/javascript; charset=utf-8" },
  "/assets/chunk-55IACEB6.js": { body: a10, type: "application/javascript; charset=utf-8" },
  "/assets/chunk-EDXVE4YY.js": { body: a11, type: "application/javascript; charset=utf-8" },
  "/assets/chunk-FMBD7UC4.js": { body: a12, type: "application/javascript; charset=utf-8" },
  "/assets/chunk-OYMX7WX6.js": { body: a13, type: "application/javascript; charset=utf-8" },
  "/assets/chunk-QZHKN3VN.js": { body: a14, type: "application/javascript; charset=utf-8" },
  "/assets/chunk-YZCP3GAM.js": { body: a15, type: "application/javascript; charset=utf-8" },
  "/assets/classDiagram-6PBFFD2Q.js": { body: a16, type: "application/javascript; charset=utf-8" },
  "/assets/classDiagram-v2-HSJHXN6E.js": { body: a17, type: "application/javascript; charset=utf-8" },
  "/assets/clone.js": { body: a18, type: "application/javascript; charset=utf-8" },
  "/assets/cose-bilkent-S5V4N54A.js": { body: a19, type: "application/javascript; charset=utf-8" },
  "/assets/cytoscape.esm.js": { body: a20, type: "application/javascript; charset=utf-8" },
  "/assets/dagre-KV5264BT.js": { body: a21, type: "application/javascript; charset=utf-8" },
  "/assets/defaultLocale.js": { body: a22, type: "application/javascript; charset=utf-8" },
  "/assets/diagram-5BDNPKRD.js": { body: a23, type: "application/javascript; charset=utf-8" },
  "/assets/diagram-G4DWMVQ6.js": { body: a24, type: "application/javascript; charset=utf-8" },
  "/assets/diagram-MMDJMWI5.js": { body: a25, type: "application/javascript; charset=utf-8" },
  "/assets/diagram-TYMM5635.js": { body: a26, type: "application/javascript; charset=utf-8" },
  "/assets/erDiagram-SMLLAGMA.js": { body: a27, type: "application/javascript; charset=utf-8" },
  "/assets/flowDiagram-DWJPFMVM.js": { body: a28, type: "application/javascript; charset=utf-8" },
  "/assets/ganttDiagram-T4ZO3ILL.js": { body: a29, type: "application/javascript; charset=utf-8" },
  "/assets/gitGraphDiagram-UUTBAWPF.js": { body: a30, type: "application/javascript; charset=utf-8" },
  "/assets/gpt-4o.js": { body: a31, type: "application/javascript; charset=utf-8" },
  "/assets/graph.js": { body: a32, type: "application/javascript; charset=utf-8" },
  "/assets/infoDiagram-42DDH7IO.js": { body: a33, type: "application/javascript; charset=utf-8" },
  "/assets/init.js": { body: a34, type: "application/javascript; charset=utf-8" },
  "/assets/ishikawaDiagram-UXIWVN3A.js": { body: a35, type: "application/javascript; charset=utf-8" },
  "/assets/journeyDiagram-VCZTEJTY.js": { body: a36, type: "application/javascript; charset=utf-8" },
  "/assets/kanban-definition-6JOO6SKY.js": { body: a37, type: "application/javascript; charset=utf-8" },
  "/assets/katex.js": { body: a38, type: "application/javascript; charset=utf-8" },
  "/assets/layout.js": { body: a39, type: "application/javascript; charset=utf-8" },
  "/assets/linear.js": { body: a40, type: "application/javascript; charset=utf-8" },
  "/assets/mermaid.core.js": { body: a41, type: "application/javascript; charset=utf-8" },
  "/assets/min.js": { body: a42, type: "application/javascript; charset=utf-8" },
  "/assets/mindmap-definition-QFDTVHPH.js": { body: a43, type: "application/javascript; charset=utf-8" },
  "/assets/ordinal.js": { body: a44, type: "application/javascript; charset=utf-8" },
  "/assets/pieDiagram-DEJITSTG.js": { body: a45, type: "application/javascript; charset=utf-8" },
  "/assets/quadrantDiagram-34T5L4WZ.js": { body: a46, type: "application/javascript; charset=utf-8" },
  "/assets/requirementDiagram-MS252O5E.js": { body: a47, type: "application/javascript; charset=utf-8" },
  "/assets/sankeyDiagram-XADWPNL6.js": { body: a48, type: "application/javascript; charset=utf-8" },
  "/assets/sequenceDiagram-FGHM5R23.js": { body: a49, type: "application/javascript; charset=utf-8" },
  "/assets/stateDiagram-FHFEXIEX.js": { body: a50, type: "application/javascript; charset=utf-8" },
  "/assets/stateDiagram-v2-QKLJ7IA2.js": { body: a51, type: "application/javascript; charset=utf-8" },
  "/assets/timeline-definition-GMOUNBTQ.js": { body: a52, type: "application/javascript; charset=utf-8" },
  "/assets/vennDiagram-DHZGUBPP.js": { body: a53, type: "application/javascript; charset=utf-8" },
  "/assets/wardley-RL74JXVD.js": { body: a54, type: "application/javascript; charset=utf-8" },
  "/assets/wardleyDiagram-NUSXRM2D.js": { body: a55, type: "application/javascript; charset=utf-8" },
  "/assets/xychartDiagram-5P7HB3ND.js": { body: a56, type: "application/javascript; charset=utf-8" },
  "/": { body: a57, type: "text/html; charset=utf-8" },
  "/index.html": { body: a57, type: "text/html; charset=utf-8" },
};
